name: Build wheel

on:
  push:
    # tags: 
    #   - 'v*'
    branches: 
      - master
  workflow_dispatch:


jobs:
  build-wheel:
    name: python
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        python-version:
          - "3.9"
          - "3.10"
          # - "3.11" # does not work
        platform: ["linux_x86_64"]
    env:
      UV_SYSTEM_PYTHON: 1
      DIFFVG_CUDA: 1

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - uses: Jimver/cuda-toolkit@v0.2.21
        with:
          cuda: "12.4.1"
          method: network
          sub-packages: '["nvcc", "cudart", "thrust"]'

      - name: "Set up Python"
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true
          python-version: ${{ matrix.python-version }}

      - name: Install the project
        run: uv sync --no-dev
      
      - name: Build the wheel
        run: python setup.py bdist_wheel
      
      - name: Move built wheel
        run: mv dist/*.whl dist/diffvg-${{ github.ref_name }}-${{ matrix.python-version }}-${{ matrix.platform }}.whl
      
      - name: Upload the wheel
        uses: actions/upload-artifact@v4
        with:
          name: diffvg-${{ github.ref_name }}-${{ matrix.python-version }}-${{ matrix.platform }}
          path: dist/diffvg-${{ github.ref_name }}-${{ matrix.python-version }}-${{ matrix.platform }}.whl
